### PR TITLE
added responsiveness to herosection

### PR DESCRIPTION
**Pull request by manthanmk66**
Added Responsiveness to Herosection also added the logo to navbar
image

### CODE REVIEW

**Comment by SamsShow** [comment]
can't see any changes in the preview build

**Comment by manthanmk66** [comment]
i have updated the herosection images with responsiveness also added logo in navbar
 previous Herosection look like this in mobile view

WhatsApp Image 2024-10-13 at 21 58 04_a6fdc226

**Comment by SamsShow** [comment]
try to compile all the changes in a single PR and there are some conflicts too, kindly do look into it

**Comment by manthanmk66** [comment]
yes i have checked all working fine also there is no conflict with base branch

**Comment by manthanmk66** [comment]
@SamsShow Could you please merge this PR? I have verified that there are not any code conflicts.

**Pull request merged**
